### ISSUE TITLE
Combine the site_chat.py with chatbot.

### ISSUE THREAD

**Issue by adrian97gl** [RoxanaBulai15/IVFuture#3]
Using the html and css put some actions in page. 
Using the / route in the site_chatbot import the chatbot.py logic. 

After write an word in the text label then press send button or enter and the chatbot will display an answer from the json file.

**Comment by RoxanaBulai15** [comment]
https://github.com/RoxanaBulai15/IVFuture/commit/f380d0c97efde86961c64b5397c8a2aeee7ef3d3

**Comment by adrian97gl** [comment]
Task closed.
